// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions'];
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    ADrawer: typeof import('ant-design-vue/es')['Drawer'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    ATable: typeof import('ant-design-vue/es')['Table'];
    ATabPane: typeof import('ant-design-vue/es')['TabPane'];
    ATabs: typeof import('ant-design-vue/es')['Tabs'];
    ATag: typeof import('ant-design-vue/es')['Tag'];
    ATextarea: typeof import('ant-design-vue/es')['Textarea'];
    ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
    ATree: typeof import('ant-design-vue/es')['Tree'];
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect'];
    AUpload: typeof import('ant-design-vue/es')['Upload'];
    LayoutContent: typeof import('./src/components/layoutContent.vue')['default'];
    LayOutHeader: typeof import('./src/components/layOutHeader.vue')['default'];
    LayoutNavMenu: typeof import('./src/components/layoutNavMenu.vue')['default'];
    MyTable: typeof import('./src/components/myTable.vue')['default'];
    DefineCodeValue: typeof import('./src/components/myTable/defineCodeValue.vue')['default'];
    LayoutContent: typeof import('./src/components/layoutContent.vue')['default'];
    LayOutHeader: typeof import('./src/components/layOutHeader.vue')['default'];
    LayoutNavMenu: typeof import('./src/components/layoutNavMenu.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
